<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>2.0.0</Version>
    <Company>Sinalização Viária Revit</Company>
    <Product>SinalizaBIM – Sinalização viária e urbanização para Revit 2027</Product>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
